### ISSUE TITLE
Question: How does mining work?

### ISSUE THREAD

**Issue by andreykats** [Frichetten/Specter#14]
I'm trying set this project up on my end. I got it running but confused on how to generate/mine tokens.
Can anyone offer any insight?

**Comment by Frichetten** [comment]
Hey @andreykats, that's a great question!

Unfortunately Specter doesn't have mining yet :P

That is a planned feature (in fact, that's probably the next big thing). I just haven't gotten there yet.

**Comment by andreykats** [comment]
Thanks for the reply. Looking forward to seeing this in the future.
